import { test } from 'node:test';
import assert from 'node:assert/strict';
import jwt from 'jsonwebtoken';
import { readFileSync } from 'node:fs';
import { MemoryPool } from './support/memory-pool.js';
process.env.VITALTRACK_NO_AUTOSTART = 'true';
process.env.JWT_SECRET = 'isolated-regression-test-secret-not-used-in-production';
delete process.env.GEMINI_API_KEY;
const { startServer } = await import('../server.js');

test('HTTP regression through the real Express middleware/routes, isolated SQL double', async t => {
  const pool = new MemoryPool(), app = await startServer({ pool, listen: false, apiOnly: true });
  const server = app.listen(0, '127.0.0.1');
  await new Promise(resolve => server.once('listening', resolve));
  t.after(() => new Promise(resolve => server.close(resolve)));
  const base = `http://127.0.0.1:${server.address().port}`;
  const token = id => jwt.sign({ id }, process.env.JWT_SECRET, { expiresIn: '1h' });
  const user = token(1), admin = token(2);
  const call = async (path, method = 'GET', body, auth = user) => {
    const response = await fetch(`${base}/api${path}`, { method, headers: { 'Content-Type': 'application/json', ...(auth ? { Authorization: `Bearer ${auth}` } : {}) }, ...(body === undefined ? {} : { body: JSON.stringify(body) }) });
    return { status: response.status, ...await response.json() };
  };
  const metric = (weight, date) => ({ weight, systolic: 120, diastolic: 80, heart_rate: 72, recorded_at: `${date}T00:00:00Z`, notes: 'Measured in morning' });
  await t.test('all baseline API methods and paths still exist; no frontend API route missing', () => {
    const registered = new Set(app._router.stack.filter(s => s.route).flatMap(s => Object.keys(s.route.methods).map(m => `${m.toUpperCase()} ${s.route.path}`)));
    const baseline = JSON.parse(readFileSync(new URL('./fixtures/baseline-api-routes.json', import.meta.url), 'utf8'));
    for (const { method, path } of baseline.routes) assert.ok(registered.has(`${method} ${path}`), `Removed route: ${method} ${path}`);
    for (const route of ['GET /api/admin/telemetry', 'PUT /api/admin/telemetry/:id', 'DELETE /api/admin/telemetry/:id', 'GET /api/admin/ai-reviews', 'PUT /api/admin/ai-reviews/:id', 'DELETE /api/admin/devices/:deviceId', 'GET /api/admin/audit-logs', 'GET /api/admin/audit-logs/:id', 'GET /api/admin/logs', 'GET /api/admin/sessions', 'DELETE /api/admin/sessions/:id']) assert.ok(registered.has(route), route);
  });
  await t.test('401/403/404 and expired JWT', async () => {
    assert.equal((await call('/health', 'GET', undefined, null)).status, 401);
    assert.equal((await call('/admin/users')).status, 403);
    assert.equal((await call('/health/999', 'DELETE')).status, 404);
    assert.equal((await call('/missing')).status, 404);
    assert.equal((await call('/health', 'GET', undefined, jwt.sign({ id: 1 }, process.env.JWT_SECRET, { expiresIn: -1 }))).status, 401);
  });
  await t.test('register/login/profile/password/logout and production-disabled demo auth', async () => {
    assert.equal((await call('/auth/register', 'POST', { full_name: 'QA', email: 'bad', password: 'abc' }, null)).status, 400);
    const registered = await call('/auth/register', 'POST', { full_name: 'New QA', email: 'newqa@example.test', password: 'Password123!' }, null);
    assert.equal(registered.status, 201); assert.ok(registered.data.token);
    assert.equal(pool.tables.users.find(u => u.id === registered.data.user.id).base_weight_kg, null);
    assert.equal(pool.tables.goals.filter(g => g.user_id === registered.data.user.id).length, 0);
    const login = await call('/auth/login', 'POST', { email: 'qa@example.test', password: 'Password123!' }, null);
    assert.equal(login.status, 200); assert.ok(!('password' in login.data.user));
    const before = pool.tables.audit_logs.length;
    const profile = await call('/profile', 'PUT', { full_name: 'QA Updated', base_weight_kg: 71, target_weight_kg: 64 });
    assert.equal(profile.status, 200); assert.equal(profile.data.base_weight_kg, 71); assert.equal(profile.data.target_weight_kg, 64);
    assert.equal(pool.tables.audit_logs.length - before, 1, 'one audit entry per mutation');
    assert.equal((await call('/profile', 'PUT', { date_of_birth: '2026-02-30' })).status, 400);
    assert.equal((await call('/profile/password', 'PUT', { old_password: 'wrong', new_password: 'NewPassword123!' })).status, 400);
    assert.equal((await call('/profile/password', 'PUT', { old_password: 'Password123!', new_password: 'NewPassword123!' })).status, 200);
    assert.equal((await call('/auth/logout', 'POST', {}, login.data.token)).status, 200);
    assert.equal((await call('/auth/me', 'GET', undefined, login.data.token)).status, 401);
    assert.equal((await call('/auth/social-login', 'POST', { email: 'admin@example.test' }, null)).status, 503);
    assert.equal((await call('/auth/otp/send', 'POST', { identifier: 'admin@example.test' }, null)).status, 503);
  });
  let first, latest, goal;
  await t.test('empty health, missing-data guidance and goal creation', async () => {
    assert.equal((await call('/health/latest')).data.latest, null);
    assert.equal((await call('/goals', 'POST', { title: 'Lose weight', target_value: 65, metric_type: 'weight' })).status, 409);
    first = (await call('/health', 'POST', metric(70, '2026-01-01'))).data;
    await call('/health', 'POST', metric(69, '2026-01-05'));
    latest = (await call('/health', 'POST', metric(68, '2026-01-10'))).data;
    assert.ok(latest?.id);
    const created = await call('/goals', 'POST', { title: 'Lose weight', metric_type: 'weight', target_value: 65 });
    assert.equal(created.status, 201); goal = created.data;
    assert.equal(goal.start_value, 68); assert.equal(goal.current_value, 68);
    assert.equal((await call('/auth/me')).data.current_health.current.weight.value, 68);
  });
  await t.test('editing/backdating/deleting never confuse measurement time with write time', async () => {
    assert.equal((await call(`/health/${first.id}`, 'PUT', { weight: 71 })).status, 200);
    assert.equal((await call('/health/latest')).data.current.weight.value, 68);
    await call('/health', 'POST', metric(73, '2026-01-02'));
    assert.equal((await call('/goals')).data[0].current_value, 68);
    await call(`/health/${latest.id}`, 'DELETE');
    assert.equal((await call('/health/latest')).data.current.weight.value, 69);
    assert.equal((await call('/goals')).data[0].start_value, 68);
    const partial = await call('/health', 'POST', { heart_rate: 76, notes: 'Pulse only' });
    assert.equal(partial.status, 201); assert.equal(partial.data.weight, null);
    assert.equal((await call('/health/latest')).data.current.weight.value, 69);
    assert.equal((await call('/goals')).data[0].progress_percentage, 0, 'moving away must not advance progress');
    assert.equal((await call('/goals/' + goal.id, 'PUT', { current_value: 66 })).status, 409);
    assert.equal((await call('/goals/' + goal.id, 'PUT', { title: 'Updated goal', target_value: 64 })).status, 200);
    assert.equal((await call('/health/1', 'PUT', { weight: 0 })).status, 400);
    assert.equal((await call('/health', 'POST', { weight: 0 })).status, 400);
    assert.equal((await call('/health', 'POST', { weight: 70, recorded_at: 'bad-date' })).status, 400);
  });
  await t.test('ownership of health/goals/devices and all supported device enums', async () => {
    assert.equal((await call(`/health/${first.id}`, 'PUT', { weight: 72 }, token(3))).status, 404);
    assert.equal((await call(`/goals/${goal.id}`, 'DELETE', undefined, token(3))).status, 404);
    assert.equal((await call('/devices/pair', 'POST', { name: 'Bad type', type: 'other' })).status, 400);
    assert.equal((await call('/devices/pair', 'POST', { name: 'Bad MAC', type: 'smartwatch', macAddress: 'bad' })).status, 400);
    const device = await call('/devices/pair', 'POST', { name: 'QA scale', type: 'smart_scale' });
    assert.equal(device.status, 201); assert.equal(device.data.status, 'idle'); assert.equal(device.data.macAddress, null);
    const count = pool.tables.health_records.length;
    assert.equal((await call(`/devices/${device.data.id}/sync`, 'POST', {})).status, 409);
    assert.equal(pool.tables.health_records.length, count, 'empty sync cannot manufacture records');
    assert.equal((await call('/devices/ingest', 'POST', { deviceId: device.data.id, weight: 67 }, token(3))).status, 404);
    assert.equal((await call('/devices/ingest', 'POST', { deviceId: device.data.id, weight: 67 })).status, 201);
    assert.equal((await call('/health/latest')).data.current.weight.value, 67);
    assert.equal((await call('/devices/' + device.data.id, 'DELETE')).status, 200);
  });
  await t.test('reminder CRUD, completion, timezone and disabled schedules', async () => {
    const created = await call('/reminders', 'POST', { type: 'measurement', title: 'Measure', time_of_day: '08:00', timezone: 'Asia/Ho_Chi_Minh', repeat_days: [0, 1, 2, 3, 4, 5, 6] });
    assert.equal(created.status, 201);
    const id = created.data.id;
    assert.equal((await call('/reminders/' + id, 'PUT', { complete: true })).status, 200);
    assert.equal(JSON.parse(pool.tables.reminders.find(r => r.id === id).completed_dates).length, 1);
    await call('/reminders/' + id, 'PUT', { complete: true });
    assert.equal(JSON.parse(pool.tables.reminders.find(r => r.id === id).completed_dates).length, 1, 'completion deduplicated');
    await call('/reminders/' + id, 'PUT', { is_active: false });
    assert.equal((await call('/reminders/' + id, 'PUT', { complete: true })).status, 400);
    assert.equal((await call('/reminders', 'POST', { type: 'water', title: 'Drink', time_of_day: '25:00' })).status, 400);
    assert.equal((await call('/reminders/' + id, 'DELETE')).status, 200);
  });
  await t.test('Vietnamese and four-byte Unicode survive goal, reminder and note create/read/update', async () => {
    const title = 'Kiểm soát cân nặng tiêu chuẩn — 🫀';
    const created = await call('/goals', 'POST', { title, metric_type: 'weight', target_value: 65 });
    assert.equal(created.status, 201); assert.equal(created.data.title, title);
    assert.equal((await call('/goals')).data.find(g => g.id === created.data.id).title, title);
    const updatedTitle = 'Mục tiêu giảm cân đều đặn — 🫀';
    assert.equal((await call('/goals/' + created.data.id, 'PUT', { title: updatedTitle })).data.title, updatedTitle);
    const reminderTitle = 'Uống nước ấm buổi sáng — 💧';
    const reminder = await call('/reminders', 'POST', { title: reminderTitle, type: 'water', time_of_day: '08:00' });
    assert.equal(reminder.status, 201);
    assert.equal((await call('/reminders')).data.find(r => r.id === reminder.data.id).title, reminderTitle);
    const notes = 'Đo sau khi tập thể dục, cảm thấy khỏe — 🫀';
    const recorded = await call('/health', 'POST', { weight: 67, notes });
    assert.equal(recorded.status, 201); assert.equal(recorded.data.notes, notes);
    assert.equal((await call('/health')).data.find(r => r.id === recorded.data.id).notes, notes);
    await call('/health/' + recorded.data.id, 'DELETE');
    await call('/reminders/' + reminder.data.id, 'DELETE');
    await call('/goals/' + created.data.id, 'DELETE');
  });
  await t.test('AI saves real history, uses actual user data, never fakes a successful save', async () => {
    const result = await call('/ai/diagnose', 'POST', { symptoms: ['Tức ngực'], use_database: true });
    assert.equal(result.status, 200); assert.equal(result.data.riskLevel, 'critical'); assert.equal(result.data.dataSource, 'mysql');
    assert.equal(result.data.riskScore, null); assert.ok(result.data.sources.every(s => s.url.startsWith('https://www.heart.org/')));
    assert.equal((await call('/ai/history')).data[0].id, result.data.id);
    assert.equal((await call('/ai/history', 'GET', undefined, token(3))).data.length, 0);
    assert.equal((await call('/admin/ai-reviews', 'GET', undefined, admin)).data.length, 1);
    assert.equal((await call('/admin/ai-reviews/' + result.data.id, 'PUT', { physician_reviewed: true, physician_notes: 'Reviewed' }, admin)).status, 200);
  });
  await t.test('admin dossier/telemetry/export contain database data and protect sensitive fields', async () => {
    const users = await call('/admin/users', 'GET', undefined, admin);
    assert.ok(users.data.every(row => row.id && row.full_name && !('password' in row)));
    const dossier = await call('/admin/users/1/dossier', 'GET', undefined, admin);
    assert.equal(dossier.status, 200); assert.ok(Array.isArray(dossier.data.health_records));
    assert.ok(Array.isArray(dossier.data.aiHistory)); assert.ok(dossier.data.stats);
    assert.equal(dossier.data.user.current_health.current.weight.value, 67);
    assert.equal((await call('/admin/telemetry', 'GET', undefined, admin)).status, 200);
    const exported = await call('/admin/export', 'GET', undefined, admin);
    assert.equal(exported.status, 200); assert.equal(exported.data.source, 'mysql');
    assert.ok(exported.data.users.every(u => !('password' in u)));
    assert.ok(exported.data.healthRecords.length > 0);
    assert.equal((await call('/admin/audit-logs', 'GET', undefined, admin)).status, 200);
    assert.equal((await call('/admin/logs', 'GET', undefined, admin)).status, 200);
    assert.equal((await call('/admin/sessions', 'GET', undefined, admin)).status, 200);
  });
  await t.test('DB unavailable is 503 during authentication, not a false 401', async () => {
    pool.fail = true;
    const response = await call('/health');
    pool.fail = false;
    assert.equal(response.status, 503); assert.equal(response.success, false);
  });
  await t.test('admin saves actual profile fields, validates roles and keeps current weight independent', async () => {
    const current = (await call('/health/latest')).data.current.weight.value;
    const updated = await call('/admin/users/1', 'PUT', { height_cm: 172.5, base_weight_kg: 72, target_weight_kg: 63, primary_doctor: 'QA clinician', medical_notes: 'QA note', date_of_birth: '1990-05-15', chronic_conditions: ['QA condition'] }, admin);
    assert.equal(updated.status, 200); assert.equal(updated.data.height_cm, 172.5);
    assert.equal(updated.data.primary_doctor, 'QA clinician'); assert.equal(updated.data.current_health.current.weight.value, current);
    assert.equal(updated.data.target_weight_kg, 63);
    assert.equal((await call('/admin/users/1', 'PUT', { height_cm: 0 }, admin)).status, 400);
    assert.equal((await call('/admin/users/2', 'PUT', { role: 'user' }, admin)).status, 400);
    const created = await call('/admin/users', 'POST', { full_name: 'Admin-created QA', email: 'created@example.test', role: 'user', password: 'Password123!', primary_doctor: 'Saved clinician', base_weight_kg: null }, admin);
    assert.equal(created.status, 201); assert.equal(created.data.primary_doctor, 'Saved clinician'); assert.equal(created.data.base_weight_kg, null);
    const cleared = await call('/admin/users/1', 'PUT', { height_cm: null }, admin);
    assert.equal(cleared.data.height_cm, null);
  });
  await t.test('admin dashboard/statistics are actual counts, normalize decimals and respect the selected range', async testContext => {
    const row = { id: 999, user_id: 1, weight: '68.50', systolic: 190, diastolic: 100, heart_rate: 72, recorded_at: new Date().toISOString() };
    const saved = pool.tables.health_records;
    testContext.after(() => { pool.tables.health_records = saved; });
    pool.tables.health_records = [row];
    const dashboard = await call('/admin/dashboard', 'GET', undefined, admin);
    assert.equal(dashboard.status, 200); assert.equal(dashboard.data.totalUsers, pool.tables.users.length);
    assert.equal(Object.values(dashboard.data.riskDistribution).reduce((a, b) => a + b, 0), pool.tables.health_records.filter(r => r.systolic != null && r.diastolic != null && new Date(r.recorded_at) <= new Date()).length);
    const stats = await call('/admin/statistics?range=7d', 'GET', undefined, admin);
    assert.equal(stats.status, 200); assert.equal(stats.data.summary.overallAvgWeight, 68.5);
    assert.equal(stats.data.summary.recordsInRange, 1); assert.equal(stats.data.healthDistribution.reduce((sum, item) => sum + item.count, 0), 1);
    pool.tables.health_records = pool.tables.health_records.filter(r => r.id !== 999);
    assert.equal((await call('/admin/statistics?range=7d', 'GET', undefined, admin)).data.healthDistribution.reduce((sum, item) => sum + item.count, 0), 0);
  });
  await t.test('admin measurement review/edit/delete recalculates latest values, and session termination revokes JWT', async () => {
    const before = (await call('/health/latest')).data.current.weight.value;
    const created = await call('/health', 'POST', { weight: 66, systolic: 118, diastolic: 76, heart_rate: 72 });
    assert.equal(created.status, 201);
    const edited = await call(`/admin/telemetry/${created.data.id}`, 'PUT', { weight: 65.5, doctor_reviewed: true, doctor_notes: 'QA review' }, admin);
    assert.equal(edited.status, 200); assert.equal((await call('/health/latest')).data.current.weight.value, 65.5);
    assert.equal((await call(`/admin/telemetry/${created.data.id}`, 'PUT', { weight: null, systolic: null, diastolic: null, heart_rate: null }, admin)).status, 400);
    assert.equal((await call(`/admin/telemetry/${created.data.id}`, 'DELETE', undefined, admin)).status, 200);
    assert.equal((await call('/health/latest')).data.current.weight.value, before);
    const login = await call('/auth/login', 'POST', { email: 'other@example.test', password: 'Password123!' }, null);
    const sid = jwt.decode(login.data.token).sessionId;
    assert.equal((await call('/admin/sessions/' + sid, 'DELETE', undefined, admin)).status, 200);
    assert.equal((await call('/auth/me', 'GET', undefined, login.data.token)).status, 401);
  });
  await t.test('a failed write returns 500 and rolls back instead of reporting success', async () => {
    const before = pool.tables.health_records.length;
    pool.failPattern = /INSERT INTO health_records/;
    const response = await call('/health', 'POST', metric(67, '2026-02-01'));
    pool.failPattern = null;
    assert.equal(response.status, 500); assert.equal(response.success, false);
    assert.equal(pool.tables.health_records.length, before);
  });
});

test('existing schema supports full health records and basic reminder CRUD without running migration', async t => {
  const pool = new MemoryPool({ modern: false }), app = await startServer({ pool, listen: false, apiOnly: true });
  const server = app.listen(0, '127.0.0.1'); await new Promise(resolve => server.once('listening', resolve));
  t.after(() => new Promise(resolve => server.close(resolve)));
  const base = `http://127.0.0.1:${server.address().port}/api`, token = jwt.sign({ id: 1 }, process.env.JWT_SECRET);
  const call = async (path, method, body) => { const r = await fetch(base + path, { method, headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` }, ...(body ? { body: JSON.stringify(body) } : {}) }); return { status: r.status, ...await r.json() }; };
  assert.equal((await call('/health/latest', 'GET')).data.capabilities.partial_records, false);
  assert.equal((await call('/health', 'POST', { weight: 70 })).status, 400);
  assert.equal((await call('/health', 'POST', { weight: 70, systolic: 120, diastolic: 80, heart_rate: 72 })).status, 201);
  const r = await call('/reminders', 'POST', { type: 'water', title: 'Drink', time_of_day: '08:00' });
  assert.equal(r.status, 201);
  assert.equal((await call(`/reminders/${r.data.id}`, 'PUT', { is_active: false })).status, 200);
  assert.equal((await call(`/reminders/${r.data.id}`, 'PUT', { complete: true })).status, 409);
});
